name: CI
on:
  workflow_dispatch:  
    inputs:
      environment:
        description: 'The env to deploy infra to'
        required: true
        default: 'dev'
  
env:
  STORAGE_ACCOUNT_NAME: dmcgightesting${{ inputs.environment }}
  RESOURCE_GROUP_NAME: rg-terraform-state-${{ inputs.environment }}
  CONTAINER_NAME: tfstate-${{ inputs.environment }}
  BLOB_NAME: terraform-${{ inputs.environment }}.tfstate
  WORKING_DIRECTORY: github-deployment
  LOCATION: ukwest

permissions:
  id-token: write     # ← allows GitHub to mint an OIDC token
  contents: read      # ← still needed to check out your code
        
jobs:
  scan-terraform-config:
    runs-on: ubuntu-latest
    name: Scan Terraform/Bicep with Checov
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov Scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ env.WORKING_DIRECTORY }}
          soft_fail: false 

  
